### ISSUE TITLE
Unexpected Server Error when deployed to Vercel

### ISSUE THREAD

**Issue by xHomu** [VulcanJS/eurodance-stack#1]
Hey Eric,

Trying out this template to see how well Remix deploys to Vercel, but encounter this error on anything that involves database get/post:

![image](https://user-images.githubusercontent.com/84349818/179618566-a97bf171-155c-479e-b773-1d7ffb533c8f.png)

This is a vanilla deployment:

https://remix-vulcan.vercel.app/

I setup the environment variables based on the instruction, including 

> set DATABASE_URL to file:./tmp/data/data.db?connection_limit=1

and this is the function error:

![image](https://user-images.githubusercontent.com/84349818/179618818-a9397a5f-91eb-47ad-b401-9d8b50a41d04.png)

Did Vercel or Remix changed the way it deals with temp stores?

**Comment by eric-burel** [comment]
Hi, I haven't digged the database much at this point to be honest :/ Vercel won't let you host a SQLite database this way, so I am looking for a free host, if you know any that would help a lot.

The error you see is currently expected and "normal".

For Mongo I am using an Atlassian free tier for demos, in read only mode. Stuffs like login don't work anyway so maybe I could add a cleaner error message when I detect a local/fake database, that's also what I do in Vulcan Next.
